import * as dotenv from 'dotenv'
import './globals.css'
import { Inter } from 'next/font/google';
import { Nav, Footer } from '@/components';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <header>
          <Nav />
        </header>
        {children}
        <footer className="mt-auto">
          <Footer />
        </footer>
      </body>
    </html>
  )
}